name: flamefinder
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core:
  google_fonts:
  lottie:
  flutter_grid_button:
  firebase_auth:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pozadina.jpg
    - assets/google.png
    - assets/pozadinamain.jpg
    - assets/email.png
    - assets/historija.png
    - assets/historija.svg
    - assets/sprijecit.png
    - assets/pozar.png
